import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Drawer from './components/drawer'
import Providers from './components/Providers'
import Appbar from './components/appBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Appbar/>
          <div className='flex'>
            <Drawer/>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
